<<<<<<< HEAD
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
=======
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Good-Pr test",
  description: "Generated by MoReel",
};
>>>>>>> origin/master

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
  children: React.ReactNode
=======
  children: React.ReactNode;
>>>>>>> origin/master
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
<<<<<<< HEAD
  )
=======
  );
>>>>>>> origin/master
}
